### ISSUE TITLE
Error evaluating 'skipif': you need to specify reason=STRING when using booleans as conditions.

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [dannysepler/pytestify#42] opened 2022-07-11 09:04 UTC
When converting 

```python
import unittest

HAS_NUMPY = False

@unittest.skipUnless(HAS_NUMPY, "This test requires the numpy library.")
class TestBrain:
    def test_x(self):
        assert 42
```
The reason need to be a keyword argument when the condition is a boolean. 

Right now the result is:
```diff
--- a/b.py
+++ b/b.py
@@ -1,8 +1,9 @@
+import pytest
 import unittest

 HAS_NUMPY = False


-@unittest.skipUnless(HAS_NUMPY, "This test requires the numpy library.")
+@pytest.mark.skipif(not HAS_NUMPY, "This test requires the numpy library.")
 class TestBrain:
     def test_x(self):
         assert 42
```

Should be:
```diff
-@pytest.mark.skipif(not HAS_NUMPY, "This test requires the numpy library.")
+@pytest.mark.skipif(not HAS_NUMPY, reason="This test requires the numpy library.")
```

**Comment by dannysepler** [comment] 2022-07-14 15:46
good catch -- this is actually a duplicate of https://github.com/dannysepler/pytestify/issues/2. about time i (/ someone) got to it!

**Closed by dannysepler** 2022-07-14 15:46 UTC
